# Site settings
author: Ryan Spence
title: My GITHub Brings All the Code to the Yard
header-img: img/home-bg.png
email: planetlucid@gmail.com
copyright_name: Ryan Spence
description: > # this means to ignore newlines until "baseurl:"
  The Dev Diary of Ryan Spence
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  planetlucid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
